### ISSUE TITLE
doxdox.org is down 

### ISSUE THREAD

**Issue by worldoptimizer** [docsbydoxdox/doxdox#183]
There is a JSON parse error (500)

Best regards

**Comment by neogeek** [comment]
Sorry about that. I should be able to take a look at it tonight or tomorrow. I really can't wait to finish the rewrite as I'm hoping this issue will no longer happen.

**Comment by neogeek** [comment]
Looks like it was just an issue with the GitHub token! _phew_

**Comment by neogeek** [comment]
I should make sure the error in the rewrite is more specific as to what error is happening.

**Comment by worldoptimizer** [comment]
Thanks for putting it online again!
