### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: node_modules directory was not found

### ISSUE THREAD

**Issue by JeissonEsteban** [docsbydoxdox/doxdox#185]
I am using the 4.0.0-preview.13 version, but its not working.

`
(node:562824) UnhandledPromiseRejectionWarning: Error: node_modules directory was not found
    at file:///../node_modules/doxdox-cli/dist/src/index.js:65:15
(Use `node --trace-warnings ...` to show where the warning was created)
(node:562824) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or 
by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (
see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:562824) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js p
rocess with a non-zero exit code.
`

This error presents in issue:
[https://github.com/docsbydoxdox/doxdox/issues/106](url)

My information environment:
- Windows 10
- Node v14.15.5
- npm 6.14.11
- doxdox 4.0.0-preview.13

Excellent app!

**Comment by neogeek** [comment]
Life got away from me, and this ticket fell by the wayside, and I'm sorry for that. I have pushed a fix that should have fixed it. If anyone runs into a similar issue or the same issue, I can reopen this ticket.
