### ISSUE TITLE
Invalid layout specified when running packaged app

### ISSUE THREAD

**Issue by antoniofagardo** [docsbydoxdox/doxdox#61]
Using : 

- doxdox v2.0.3 via node js v8.9.4

- windows cmd

- Win10

 and the following code:

`doxdox.parseInputs([folder], {'parser': 'dox','layout': 'bootstrap'}).then(content => { /***/}`

When running the script directly from nodejs everything works with no issue.
Running the app packaged with nexe gives me the following error: 

`Error: Invalid layout specified.
    at findPackagePath.then.plugin (C:\agv\DevWMS\Test\doc-gen.exe:699:28)
    at <anonymous>`

Maybe related to:

- Error: Invalid layout specified. #49

but the cause seems to be different

**Comment by antoniofagardo** [comment]
Posting my findings for others with similar issue.

Looks like when the electron app is packaged with electron-packager, the NODE_MODULES_DIRECTORIES const from loaders.js got messed up.

`__dirname` points to `/app/path/node_modules/doxdox/lib` 
so the first value of NODE_MODULES_DIRECTORIES will be pointing to
`/app/path/node_modules/doxdox/node_modules` 
instead of
`/app/path/node_modules`

So to find the right path for the nodes_modules directory, I had to modify
```
const NODE_MODULE_DIRECTORIES = [
    path.join(__dirname, '..', 'node_modules'),
    path.join(process.cwd(), 'node_modules')
];
```

into 

```
const NODE_MODULE_DIRECTORIES = [
    path.join(__dirname, '..', 'node_modules'),
    path.join(process.cwd(), 'node_modules'),
    path.join(__dirname, '..', '..')
];
```

I kept `path.join(__dirname,'..', 'node_modules')` just in case to not break anything else, but it looks like this is useless as it always point to a directory that doesn't exists

`path.join(process.cwd(), 'node_modules')` doesn't work either as the electron app is stored in `/path/to/electron/executable/resources/app`

**Comment by pfiaux** [comment]
maybe this helps but it looks like doxdox will first look for a custom template file with the given name, then if not found it will fallback to the plugins.

Since it validates for a file if you happen to have a folder with the same name it will fail because it's an invalid layout.

This happened to me with `--layout bootstrap` when I had a folder called bootstrap/ in my project.

Ideally the error messages for "Error: Invalid layout specified."
* plugin not found: "Error: Invalid layout plugin specified: ${config.layout}."
* template is not valid: "Error: Invalid layout specified: ${config.layout}."

**Comment by SalathielGenese** [comment]
Hello guys,

I'm new to this and was almost exited.
I tried all layout and even not explicit layout without clue.
Unlike what @pfiaux seems to point out, my folders are **src/**, **spec/**, **dist/** and **node_modules/**.

**Comment by SalathielGenese** [comment]
I had first installed `doxdox` globally ( `yarn global add doxdox` ) but after remember I faced slightly different behavior with some packages like `nodemon`, `jasmine`, `uuid` from global to local... So I tried to install locally and :
```sh
yarn add --dev doxdox
yarn run doxdox 'dist/src/**/*.js' --output DOCUMENTATION.md
```
... I got a different error. I first wanted to believe this related to my ES2015 compilant file, but it tries to apply a bad regex to my comment - _**the opening parenthesis is not escaped**_ -

```text
$ '${PROJECT_HOME}/node_modules/.bin/doxdox' 'dist/src/**/*.js' --output DOCUMENTATION.md
${PROJECT_HOME}/node_modules/dox/lib/dox.js:300
    , matchType = new RegExp('^@?' + type + ' *')
                  ^

SyntaxError: Invalid regular expression: /^@?Singleton( */: Unterminated group
    at new RegExp (<anonymous>)
    at exports.parseTag (${PROJECT_HOME}/node_modules/dox/lib/dox.js:300:19)
    at Array.map (<anonymous>)
    at Object.exports.parseComment (${PROJECT_HOME}/node_modules/dox/lib/dox.js:210:34)
    at Object.exports.parseComments (${PROJECT_HOME}/node_modules/dox/lib/dox.js:94:25)
    at parser (${PROJECT_HOME}/node_modules/doxdox-parser-dox/index.js:55:9)
    at fs.readFile (${PROJECT_HOME}/node_modules/doxdox/lib/doxdox.js:46:28)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by neogeek** [comment]
Window support has been improved in version v4.0.0-preview.2 and this should no longer be an issue. Feel free to re-open if the issue persists.
