### ISSUE TITLE
async function support

### ISSUE THREAD

**Issue by marcus13345** [docsbydoxdox/doxdox#63]
currently, async functions inside of classes seem to be ignored, while literal `async function`s get parsed correctly.

Test case: [JS and package.json Gist](https://gist.github.com/marcus13345/29fc49dbb52c5a651e1cff4378813a6e)
output: [Markdown Gist](https://gist.github.com/marcus13345/5ce1d81e4bc7d29786ee6f2e4f1af461)

**Comment by SferaDev** [comment]
The issue is not with doxdox, seems dox marks those functions with context == false and doxdox-parser-dox ignores them

**Comment by superliwei** [comment]
i got this issue too.

**Comment by neogeek** [comment]
This appears to be parsed correctly in the latest release v4.0.0-preview.2

```
# doxdox-test



## foo()

does foo

### Parameters

| Name | Types | Description |
| ---- | ----- | ----------- |

### Returns



## bar()

does bar

### Parameters

| Name | Types | Description |
| ---- | ----- | ----------- |

### Returns



## baz()

does baz synchronously

### Parameters

| Name | Types | Description |
| ---- | ----- | ----------- |

### Returns



## abaz()

does baz async

### Parameters

| Name | Types | Description |
| ---- | ----- | ----------- |

### Returns
```
