### ISSUE TITLE
Incoherent dependencies

### ISSUE THREAD

**Issue by Rudloff** [docsbydoxdox/doxdox#88]
Hello,

It seems doxdox 3.0 requires versions of the plugins that themselves require doxdox 2.0 and this makes Yarn throw an error:
```
error "doxdox#doxdox-parser-dox#doxdox@~2.0.3" doesn't satisfy found match of "doxdox@3.0.0"
error "doxdox#doxdox-plugin-bootstrap#doxdox@~2.0.3" doesn't satisfy found match of "doxdox@3.0.0"
error "doxdox#doxdox-plugin-handlebars#doxdox@~2.0.3" doesn't satisfy found match of "doxdox@3.0.0"
error "doxdox#doxdox-plugin-markdown#doxdox@~2.0.3" doesn't satisfy found match of "doxdox@3.0.0"
error Found 4 errors.
```

It stills installs the package correctly, but it might be worth checking.

**Comment by neogeek** [comment]
This should be resolved in the latest preview version. We have moved to using npm workspaces so all packages will now share the same release cycle, so this shouldn't be a problem in the future.
