### ISSUE TITLE
[feature] Windows support

### ISSUE THREAD

**Issue by DoubleU23** [docsbydoxdox/doxdox#92]
__problem__
windows can't handle the path regExp

__command__  
`$ npx doxdox './src/**/*.js' --layout markdown --output testDOCU.md`

__result__
`Invalid regular expression: /^(C:\xampp\htdocs\projects\viewar\viewar-docu/|./)/: Invalid escape`

**Comment by kate-codes** [comment]
Same here it looks like it might be an issue with this --> https://github.com/nodejs/node/issues/8237

**Comment by neogeek** [comment]
This should no longer be an issue as of doxdox v4.0.0-preview.2
