### ISSUE TITLE
Not supported enumeration (type union)

### ISSUE THREAD

**Issue by whalemare** [docsbydoxdox/doxdox#95]
I have function like this:
`myfile.js`
```js
  /**
   * Some description
   * @param {('SUCCESS'|'ERROR')} result
   */
  export function methodName(result) {
    // some code
  }
```

When I run `doxdox 'myfile.js' --output output.md` it is crashed with error:

```
TypeLexerSyntaxError: Expected "!", "(", "*", "...", "=", "?", "function", "module", "{", [ \t\r\n ] or [a-zA-Z_$] but "'" found.:
('SUCCESS'|'ERROR')
```

[type union in JSDoc supported from 2004](https://jsdoc.app/tags-type.html)

**Comment by neogeek** [comment]
With the latest release of doxdox (v4.0.0-preview.1) the default parser is JSDoc so type unions are now supported.
