### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by sbrl** [docsbydoxdox/doxdox#98]
I wanted to view the [api reference for GPU.js](https://doxdox.org/gpujs/gpu.js/) which is hosted on your website, but it appears to be down. I see this:

![image](https://user-images.githubusercontent.com/9929737/103161911-f692e300-47e0-11eb-8f28-203a6d835889.png)

**Comment by worldoptimizer** [comment]
Anybody? How can we get this up again? It is such a useful project?

**Comment by sbrl** [comment]
Looks like it's mysteriously started working again, but I'm hesitant to close this without a response from an org owner / member about what happened.

**Comment by neogeek** [comment]
Website should be up and stable as of right now. I plan on rebuilding the website to improve stability and improve error handling.

**Comment by worldoptimizer** [comment]
This is great news ... Thank You! Very much appreciated! 🎼🙏🖖🏽
